# Generated by Django 5.0.2 on 2024-03-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(
                choices=[('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'), ('transfer', 'Transfer')],
                max_length=20),
        ),
    ]
