# Generated by Django 5.0.2 on 2024-03-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='status',
            field=models.CharField(
                choices=[('in_stock', 'In stock'), ('new_sale', 'New sale'), ('collected', 'Collected'),
                         ('return', 'Return'), ('swap', 'Device swap'), ('Internal use', 'Out-of-stock(Internal use)')],
                default='in_stock', max_length=50),
        ),
    ]
