# Generated by Django 5.0.1 on 2024-04-04 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_router_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('event_type', models.CharField(choices=[('received', 'Received'), ('new_sale', 'New Sale'), ('collection', 'Collection'), ('swop_out', 'Swop-Out'), ('return', 'Return'), ('transfer', 'Transfer'), ('returned_CCD', 'Returned CCD'), ('internal_dist', 'Internal Distribution')], max_length=50, null=True)),
                ('serial_number', models.CharField(max_length=150, null=True)),
                ('status_from', models.CharField(choices=[('in_stock', 'In-Stock'), ('onboarded', 'Onboarded'), ('returned', 'Returned'), ('to_refurb', 'To-Refurb')], default='in_stock', max_length=50)),
                ('status_to', models.CharField(choices=[('in_stock', 'In-Stock'), ('onboarded', 'Onboarded'), ('returned', 'Returned'), ('to_refurb', 'To-Refurb')], default='in_stock', max_length=50)),
                ('message', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.AddField(
            model_name='router',
            name='event_type',
            field=models.CharField(choices=[('received', 'Received'), ('new_sale', 'New Sale'), ('collection', 'Collection'), ('swop_out', 'Swop-Out'), ('return', 'Return'), ('transfer', 'Transfer'), ('returned_CCD', 'Returned CCD'), ('internal_dist', 'Internal Distribution')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='router',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_full',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='serial_number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In-Stock'), ('new_sale', 'New sale'), ('collected', 'Collected'), ('onboarded', 'Onboarded'), ('swap', 'Device swap'), ('returned', 'Returned'), ('to_refurb', 'To-Refurb'), ('Internal use', 'Out-of-stock(Internal use)')], default='in_stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
