# Generated by Django 5.0.1 on 2024-07-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='serial_number',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('store_manager', 'Store manager'), ('senior_management', 'Senior management'), ('store_assistant', 'Store Assistant')], default='store_manager', max_length=150, null=True),
        ),
    ]
