# Generated by Django 5.0.1 on 2024-09-26 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_router_serial_number_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='action',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='action',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.store'),
        ),
        migrations.AlterField(
            model_name='faileduploads',
            name='event_type',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('new_sale', 'New Sale'), ('collection', 'Collection'), ('swop_out', 'Swop-Out'), ('return', 'Return'), ('transfer', 'Transfer'), ('returned_CCD', 'Returned CCD'), ('internal_dist', 'Internal Distribution')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='faileduploads',
            name='message',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='faileduploads',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='log',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='log',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='router',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='emei',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='router',
            name='event_type',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('new_sale', 'New Sale'), ('collection', 'Collection'), ('swop_out', 'Swop-Out'), ('return', 'Return'), ('transfer', 'Transfer'), ('returned_CCD', 'Returned CCD'), ('internal_dist', 'Internal Distribution')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='router',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='name_full',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('store_manager', 'Store manager'), ('senior_management', 'Senior management'), ('store_assistant', 'Store Assistant')], default='store_manager', max_length=150),
        ),
    ]
