# Generated by Django 5.0.1 on 2024-02-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_emei_log_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('store_manager', 'Store manager'), ('senior_management', 'Senior management'), ('store_assistant', 'Store assistant')], max_length=150, null=True),
        ),
    ]
