---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullName" . }}
  labels:
  {{- include "labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "fullName" . }}
              port:
                name: http
