---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "fullName" . }}
  labels:
  {{- include "labels" . | nindent 4 }}
data:
{{ range $k, $v := .Values.secrets }}
  {{ $k | upper }}: {{ $v | toString | b64enc }}
{{ end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "fullName" . }}-redis
  labels:
  {{- include "redisLabels" . | nindent 4 }}
data:
{{ range $k, $v := .Values.secretsRedis }}
  {{ $k | upper }}: {{ $v | toString | b64enc }}
{{ end }}
