---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fullName" . }}
  labels:
  {{- include "labels" . | nindent 4 }}
imagePullSecrets:
  {{- .Values.imagePullSecrets | toYaml | nindent 2 }}
