---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fullName" . }}-redis-master
  labels:
    {{- include "redisMasterLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "redisMasterLabels" . | nindent 6 }}
  serviceName: {{ include "fullName" . }}-redis-headless
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "redisMasterLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1001
      serviceAccountName: {{ include "fullName" . }}
      containers:
        - name: redis
          image: harbor.cicd.rain.co.za/docker.io/bitnami/redis:6.2.6-debian-10-r97
          imagePullPolicy: "Always"
          securityContext:
            runAsUser: 1001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          command:
            - /bin/bash
          args:
            - -c
            - /opt/bitnami/scripts/start-scripts/start-master.sh
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: REDIS_REPLICATION_MODE
              value: master
            - name: ALLOW_EMPTY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fullName" . }}-redis
                  key: ALLOW_EMPTY_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fullName" . }}-redis
                  key: REDIS_PASSWORD
            - name: REDIS_TLS_ENABLED
              value: "no"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /health/ping_liveness_local.sh 5
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /health/ping_readiness_local.sh 1
          resources:
            {{ .Values.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: start-scripts
              mountPath: /opt/bitnami/scripts/start-scripts
            - name: health
              mountPath: /health
            - name: redis-data
              mountPath: /data
              subPath: 
            - name: config
              mountPath: /opt/bitnami/redis/mounted-etc
            - name: redis-tmp-conf
              mountPath: /opt/bitnami/redis/etc/
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: start-scripts
          configMap:
            name: {{ include "fullName" . }}-redis-scripts
            defaultMode: 0755
        - name: health
          configMap:
            name: {{ include "fullName" . }}-redis-health
            defaultMode: 0755
        - name: config
          configMap:
            name: {{ include "fullName" . }}-redis-configuration
        - name: redis-tmp-conf
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: redis-data
          emptyDir: {}
