class RESPONSES:
    SUCCESS = "Success"
    ALREADY_IN_STOCK = "Router already in-stock"
    ONBOARDED_AND_ASSIGNED = "Router currently onboarded and assigned to customer"
    NEVER_ASSIGNED = "Router was never assigned to a customer"
    ALREADY_RETURNED = "Router has already been returned"
    TO_BE_RETURNED = "Router is set to be returned to CCD"
    NOT_SCANNED = "Router has not been scanned into stock"
    ALLOCATED_TO_ORDER = "Router is already allocated to an order"
    NEW_DEVICE_RETURN = "Router is a return - Please issue a new device"
    NEW_DEVICE_CCD = "Router is set to be returned to CCD - Please issue a new device"
    INSTOCK_NO_RETURN_TO_CCD = "Router in stock - Not eligible for return to CCD"
    BOUND_FOR_CCD = "Bound for CCD"
    RETURNED_BY_CUSTOMER = "Router returned by customer, bound for CCD"
    RETURN_NOT_ELIGIBLE_FOR_TRANSFER = "Router is a return - Not eligible for transfer"
